[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "chechess/_version.py"

[tool.black]
line-length = 99
target-version = ["py38","py39"]
